In [1]:
import numpy as np
print(np.__version__)

1.24.2


## Create a numpy array of size 10, filled with zeros.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a numpy array with values ranging from 10 to 49

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Create a numpy matrix of 2*2 integers, filled with ones

In [7]:
np.ones([2,2], dtype=int)

array([[1, 1],
       [1, 1]])

## Create a numpy matrix of 3*2 float numbers, filled with ones.

In [10]:
np.ones([3,2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [13]:
x = np.arange(4, dtype=int)
x

array([0, 1, 2, 3])

In [12]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [14]:
np.ones_like(x)

array([1, 1, 1, 1])

## Create a numpy matrix of 4*4 integers, filled with fives.

In [16]:
np.ones([4, 4], dtype=int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

## Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create a numpy array, filled with 3 random integer values between 1 and 10.

In [18]:
np.random.randint(1, 10, 3)

array([6, 5, 1])

In [19]:
np.random.randint(10, size=3)

array([7, 9, 1])

## Create a 3 * 3 * 3 numpy matrix, filled with random float values.

In [21]:
np.random.randn(3,3,3)

array([[[ 0.80180427, -1.26591413,  0.81050085],
        [-0.06657624, -1.20478268,  0.16341926],
        [ 0.52951874, -0.9619195 ,  0.79245298]],

       [[ 1.07907585, -0.23889419, -1.91416011],
        [-0.63690585, -0.22465488, -0.17670178],
        [-0.14110949, -1.54843348, -1.52946072]],

       [[-0.95881625, -1.80126234, -0.17241373],
        [ 0.0710858 ,  0.95940029, -0.05239786],
        [ 0.22816713,  1.7043605 , -0.70125807]]])

## Given the X python list convert it to an Y numpy array

In [22]:
X = [1, 2, 3]
print(X, type(X))

[1, 2, 3] <class 'list'>


In [23]:
y = np.array(x)
print(y, type(y))

[0 1 2 3] <class 'numpy.ndarray'>


## Check the identity number of y

In [24]:
print(id(y))

430390376944


In [25]:
help(id)

Help on built-in function id in module builtins:

id(obj, /)
    Return the identity of an object.
    
    This is guaranteed to be unique among simultaneously existing objects.
    (CPython uses the object's memory address.)



## Create a numpy array with the odd numbers between 1 to 10

In [27]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## Create a numpy array with numbers from 1 to 10, in descending order.

In [32]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [35]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

### The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

### If a list containing less than 9 elements is passed into the function, it should raise a ValueError exception with the message: "List must contain nine numbers." The values in the returned dictionary should be lists and not Numpy arrays.

In [2]:
import numpy as np

lst = [1,2,3,4,5,6,7,8,9]

In [6]:
def calculate(l):
    
    if len(l) > 9:
        raise ValueError("List must contain nine numbers")
    else:
        array = np.reshape(l, (3,3))
    
        mean1 = np.mean(array, axis=1)
        mean2 = np.mean(array, axis=0)
        flatmean = np.mean(array.flatten())
    
        var1 = np.var(array, axis=1)
        var2 = np.var(array, axis=0)
        flatvar = np.var(array)
    
        std1 = np.std(array, axis=1)
        std2 = np.std(array, axis=0)
        flatstd = np.std(array)
    
        max1 = np.max(array, axis=1)
        max2 = np.max(array, axis=0)
        flatmax = np.max(array)
    
        min1 = np.min(array, axis=1)
        min2 = np.min(array, axis=0)
        flatmin = np.min(array)
    
        sum1 = np.sum(array, axis=1)
        sum2 = np.sum(array, axis=0)
        flatsum = np.sum(array)
    
        dic = { 'mean' : [[mean1], [mean2], [flatmean]],
                'var'  : [[var1], [var2], [flatvar]],
                'std'  : [[std1], [std2], [flatstd]],
                'maxi' : [[max1], [max2], [flatmax]],
                'mini' : [[min1], [min2], [flatmin]],
                'sums' : [[sum1], [sum2], [flatsum]] }
    
    
        return dic
    

In [7]:
newlst = [1,2,3,4,5,6,7,8]

In [19]:
calculate(lst)

{'mean': [[array([1., 4., 7.])], [array([3., 4., 5.])], [4.0]],
 'var': [[array([0.66666667, 0.66666667, 0.66666667])],
  [array([6., 6., 6.])],
  [6.666666666666667]],
 'std': [[array([0.81649658, 0.81649658, 0.81649658])],
  [array([2.44948974, 2.44948974, 2.44948974])],
  [2.581988897471611]],
 'maxi': [[array([2, 5, 8])], [array([6, 7, 8])], [8]],
 'mini': [[array([0, 3, 6])], [array([0, 1, 2])], [0]],
 'sums': [[array([ 3, 12, 21])], [array([ 9, 12, 15])], [36]]}

In [6]:
lst = [0,1,2,3,4,5,6,7,8]

In [7]:
def new_calculator(ls):
    if len(ls) > 9:
        raise ValueError("List should contain nine numbers")
    else:
        mean_rows = ([ls[[0,1,2]].mean(), ls[[3,4,5]].mean(), ls[[6,7,8]].mean()])
        mean_columns = ([ls[[0,3,6]].mean(), ls[[1,4,7]].mean(), ls[[2,5,8]].mean()])
        
        var_rows = ([ls[[0,1,2]].var(), ls[[3,4,5]].var(), ls[[6,7,8]].var()])
        var_columns = ([ls[[0,3,6]].var(), ls[[1,4,7]].var(), ls[[2,5,8]].var()])
        
        std_rows = ([ls[[0,1,2]].std(), ls[[3,4,5]].std(), ls[[6,7,8]].std()])
        std_columns = ([ls[[0,3,6]].std(), ls[[1,4,7]].std(), ls[[2,5,8]].std()])
        
        max_rows = ([ls[[0,1,2]].max(), ls[[3,4,5]].max(), ls[[6,7,8]].max()])
        max_columns = ([ls[[0,3,6]].max(), ls[[1,4,7]].max(), ls[[2,5,8]].max()])
        
        min_rows = ([ls[[0,1,2]].min(), ls[[3,4,5]].min(), ls[[6,7,8]].min()])
        min_columns = ([ls[[0,3,6]].max(), ls[[1,4,7]].min(), ls[[2,5,8]].min()])
        
        sum_rows = ([ls[[0,1,2]].sum(), ls[[3,4,5]].sum(), ls[[6,7,8]].sum()])
        sum_columns = ([ls[[0,3,6]].sum(), ls[[1,4,7]].sum(), ls[[2,5,8]].sum()])
        
        return{'mean': [mean_columns, mean_rows, ls.mean()],
              'variance': [var_columns, var_rows, ls.var()],
              'standard deviation': [std_columns, std_rows, ls.std()],
              'max': [max_columns, max_rows, ls.max()],
              'min': [min_columns, min_rows, ls.rows()],
              'sum': [sum_columns, sum_rows, ls.sum()]}
            

In [8]:
new_calculator(lst)

TypeError: list indices must be integers or slices, not list

In [9]:
a = [0,1,2,3,4,5,6,7,8]
b = np.array(a).reshape(3, 3)
print(a)
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
def calculate(l):
    if len(l) != 9:
        raise ValueError("List must contain nine numbers")
        
    
    arr = np.array(l).reshape(3, 3)
    
    
    mean = [list(np.mean(arr, axis=0)), list(np.mean(arr, axis=1)), np.mean(arr)]
    variance = [list(np.var(arr, axis=0)), list(np.var(arr, axis=1)), np.var(arr)]
    std = [list(np.std(arr, axis=0)), list(np.std(arr, axis=1)), np.std(arr)]
    max_val = [list(np.max(arr, axis=0)), list(np.max(arr, axis=1)), np.max(arr)]
    min_val = [list(np.min(arr, axis=0)), list(np.min(arr, axis=1)), np.min(arr)]
    sum_val = [list(np.sum(arr, axis=0)), list(np.sum(arr, axis=1)), np.sum(arr)]
    
    
    result = {'mean': mean,
              'variance': variance,
              'standard deviation': std,
              'max': max_val,
              'min': min_val,
              'sum': sum_val}
    
    return result

In [12]:
calculate(a)

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}

In [13]:
import numpy as np

def calculate(l):
    if len(l) != 9:
        raise ValueError("List must contain nine numbers")
        
    
    arr = np.array(l).reshape(3, 3)
    
    
    mean = [list(np.mean(arr, axis=0)), list(np.mean(arr, axis=1)), np.mean(arr)]
    variance = [list(np.var(arr, axis=0)), list(np.var(arr, axis=1)), np.var(arr)]
    std = [list(np.std(arr, axis=0)), list(np.std(arr, axis=1)), np.std(arr)]
    max_val = [list(np.max(arr, axis=0)), list(np.max(arr, axis=1)), np.max(arr)]
    min_val = [list(np.min(arr, axis=0)), list(np.min(arr, axis=1)), np.min(arr)]
    sum_val = [list(np.sum(arr, axis=0)), list(np.sum(arr, axis=1)), np.sum(arr)]
    
    
    result = {'mean': mean,
              'variance': variance,
              'standard deviation': std,
              'max': max_val,
              'min': min_val,
              'sum': sum_val}
    
    return result


answer = calculate([0,1,2,3,4,5,6,7,8])
print(answer)

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}


In [1]:
for i in range(2.0):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [2]:
for i in '':
    print(i)

In [3]:
min = 1

In [4]:
min

1